# Generated by Django 4.2.6 on 2023-10-17 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateField(
                        default=datetime.datetime(2023, 10, 17, 21, 0, 45, 499974),
                        verbose_name="Дата и время",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "strong_sides",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сильные стороны"
                    ),
                ),
                (
                    "weak_sides",
                    models.TextField(
                        blank=True, null=True, verbose_name="Слабые стороны"
                    ),
                ),
                (
                    "illnesses",
                    models.TextField(blank=True, null=True, verbose_name="Болезни"),
                ),
                (
                    "injuries",
                    models.TextField(blank=True, null=True, verbose_name="Травмы"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Тренер",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date(2023, 10, 17),
                        verbose_name="Дата тренировки",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberTrains",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.member",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mainApp.train",
                        verbose_name="Тренировка",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberGames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.game",
                        verbose_name="Игра",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.member",
                        verbose_name="Игрок",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="mainApp.positions",
                verbose_name="Позиция(роль)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.team",
                verbose_name="Команда",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="guests",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="mainApp.team",
                verbose_name="Гости",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="owners",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="mainApp.team",
                verbose_name="Хозяева",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.team",
                verbose_name="Победитель",
            ),
        ),
    ]
