# Generated by Django 4.2.6 on 2023-10-17 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="datetime",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 17, 21, 4, 25, 141353),
                verbose_name="Дата и время",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="train",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Тренер",
            ),
        ),
    ]
