# Generated by Django 4.2.6 on 2023-10-17 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_team_owner_alter_game_datetime_alter_team_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="mainApp/teams/logo/", verbose_name="Флаг"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="datetime",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 17, 21, 27, 6, 837680),
                verbose_name="Дата и время",
            ),
        ),
    ]
